name: 'Terraform - Lint'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'

jobs:
  lint:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform check format
        run: terraform fmt -check -diff -recursive
